name: Azure Static Web App CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: "b4a6b406b4e46109179b45979a162973ceef61b5de179c47e6bc88d960b96ab706-d1b09c9f-86b1-4b40-a86d-73ca2dd0d10400009040dcf7e900"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "apps/portal"
          api_location: ""
          output_location: ".next"
          app_build_command: "npm run build"
          api_build_command: ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: "b4a6b406b4e46109179b45979a162973ceef61b5de179c47e6bc88d960b96ab706-d1b09c9f-86b1-4b40-a86d-73ca2dd0d10400009040dcf7e900"
          action: "close"
